### ISSUE TITLE
Erlang 19.0.3

### ISSUE THREAD

**Issue by joedevivo** [travis-ci/travis-erlang-builder#5]
Hi,

It looks like the method of `kerl` used here only picks up official releases from `erlang.org`; however, the patch releases seem to only available on github. Is there any way to get Erlang 19.0.3 working in Travis builders?

**Comment by BanzaiMan** [comment]
Thanks for taking time to open this issue.

The releases are recognized when it appears in http://erlang.org/download/. We can switch to https://github.com/erlang/otp/releases, but I have not seen a strong reason to switch yet. I note that neither lists 19.0.3.

Curiously, https://www.erlang-solutions.com/resources/download.html has 19.0.2 for Ubuntu, but we cannot use it for the reason above.

Finally, I should note that Issues here was left functional by mistake. In the future, please use https://github.com/travis-ci/travis-ci/issues to discuss anything related to this repository (besides PRs).

**Comment by joedevivo** [comment]
19.0.3 is there. You just have to click on "Show X newer tags"

<img width="815" alt="screenshot 2016-08-11 07 04 48" src="https://cloud.githubusercontent.com/assets/55951/17591194/e9446e1c-5f91-11e6-9463-2998554f67a8.png">

It's not just to test, but to bundle that version of Erlang with the artifact travis creates. If you're open to discussing further what it would take to build Erlang from the github patch releases, I'm happy to open up another issue in travis-ci/travis-ci

**Comment by BanzaiMan** [comment]
Tags are not releases, are they?

**Comment by joedevivo** [comment]
As I understand it, 19.0.3 is the latest version of Erlang, with the latest patches. I don't know why they manage the releases the way they do, but these patch releases they're tagging are the latest and greatest.

**Comment by BanzaiMan** [comment]
All right. I tried the GitHub backend, which recognizes 19.0.3. Could you try 19.0.3 and see if it works to your satisfaction?

**Comment by joedevivo** [comment]
Try it on a travis build?

**Comment by joedevivo** [comment]
It's working. Thanks so much

**Comment by joedevivo** [comment]
Will these patches get built going forward, or is it a manual process?

**Comment by BanzaiMan** [comment]
It is still a manual process (i.e., someone—most likely me—will have to initiate builds), but we can switch to the GitHub backend to look for these "unreleased" tags.

**Comment by BanzaiMan** [comment]
I'm closing this now.

As I mentioned earlier, I'll disable Issues on this repo in the near future.

Thanks.
